### ISSUE TITLE
[Xamarin.Forms Android] Can't play video after being paused (Crash)

### ISSUE THREAD

**Issue by nacompllo** [visioforge/dotnet-crossplatform-sdks-samples#2]
In the sample Xamarin.Forms repository for Android there is a crash, do the following:
1) Upload a local video from the device.
2) Play the video with the play button.
3) Pause the video with the pause button.
4) Play the video again with the play button

Following these steps you can reproduce the crash.
Crash information: System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'
More info: Tested on an emulator with Android 11.

**Comment by visioforge** [comment]
The problem has been resolved in SDK v1.1.14.
