### ISSUE TITLE
Incorrect license URL / text for a several NuGet packages

### ISSUE THREAD

**Issue by mfkl** [visioforge/dotnet-crossplatform-sdks-samples#7]
Hi,

Considering you heavily retrieved code and concepts from the libvlcsharp project (VideoView, mediaplayer APIs, dotnet events hooked to libvlc events, etc.), and you are plainly repackaging the official videolan libvlc nugets with [libvlc-nuget](https://code.videolan.org/videolan/libvlc-nuget) setup into your [own nugets](https://www.nuget.org/packages/VisioForge.CrossPlatform.Redist.iOS/), I believe it would be the _bare minimum_ to give credits where due (READMEs, visioforge website, nuget page info).

See the "MUST" section of the LGPL2.1 license https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)

**Comment by mfkl** [comment]
Actually, you're violating the terms of the LGPL2.1 for both projects, so please take those packages down.

**Comment by mfkl** [comment]
```
VisioForge.CrossPlatform.Redist.Windows.x86
VisioForge.CrossPlatform.Redist.Windows.x64
VisioForge.CrossPlatform.Controls.Uno
VisioForge.CrossPlatform.Redist.UWP.x86
VisioForge.CrossPlatform.Redist.UWP.x64
VisioForge.CrossPlatform.Redist.Android
VisioForge.CrossPlatform.Controls.XamarinForms.Platforms.WPF
VisioForge.CrossPlatform.Controls.WPF
VisioForge.CrossPlatform.Controls.XamarinForms
VisioForge.CrossPlatform.Controls.Avalonia
VisioForge.CrossPlatform.Controls.WinForms
VisioForge.CrossPlatform.Controls
VisioForge.CrossPlatform.Core
VisioForge.CrossPlatform.Redist.iOS
VisioForge.CrossPlatform.Redist.Mac
VisioForge.CrossPlatform.Redist.tvOS
```

well at least those. Maybe more.

**Comment by alexmercerind** [comment]
This is clear violation of the license under which libVLCSharp and libvlc-nuget are distributed.

Illegal.

**Comment by visioforge** [comment]
Redists packages and part of assemblies licensed under LGPL, let us update readme file and NuGet packages. We'll share all source code licensed as LGPL in a special GitHub repository in a few days. Thank you for your report.

**Comment by mfkl** [comment]
> We'll share all source code licensed as LGPL in a special GitHub repository in a few days. 

Until then you can remove those NuGet packages I listed. You have been violating the license for over a month already.

**Comment by visioforge** [comment]
We've updated license URLs / texts to correct LGPL v2.1. The problem has been resolved. Source code of packages available by request now and will be published in a special repository in a few days.

**Comment by mfkl** [comment]
> The problem has been resolved. 

No, it has not. You are still violating several terms of the LGPL license.

**Comment by visioforge** [comment]
> > The problem has been resolved.
> 
> No, it has not. You are still violating several terms of the LGPL license.

Which one?

**Comment by jeremyVignelles** [comment]
Here are a few examples, taken from [the licence](https://github.com/videolan/libvlcsharp/blob/3.x/LICENSE):

> (1.) appropriately publish on each copy an appropriate copyright notice and disclaimer of warranty; keep intact all the notices that refer to this License and to the absence of any warranty; and distribute a copy of this License along with theLibrary.

Your "attribution" (the license.txt file in [this nuget package](https://www.nuget.org/packages/VisioForge.CrossPlatform.Core/) is a copy/paste of the generic LGPL, and doesn't even mention or link LibVLCSharp

> (2.b) You must cause the files modified to carry prominent notices stating that you changed the files and the date of any change.

> 4. You may copy and distribute the Library (or a portion or derivative of it, under Section 2) in object code or executable form under the terms of Sections 1 and 2 above provided that you accompany it with the complete corresponding machine-readable source code, which must be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange.

This says that you must redistribute the source code of the library (LibVLCSharp + your hypothetical editions in that case) if you redistribute it in a binary form.

> (6.) You must give **prominent** notice with each copy of the work that the Library is used in it and that the Library and its use are covered by this License.

> (6.a) Accompany the work with the complete corresponding machine-readable source code for the Library including whatever     changes were used in the work (which must be distributed under Sections 1 and 2 above); and, if the work is an executable linked    with the Library, with the complete machine-readable "work that uses the Library", as object code and/or source code, so that the
user can modify the Library and then relink to produce a modified executable containing the modified Library.

I'm stopping here, it's already too long...

**Comment by visioforge** [comment]
(1) Each package contains "Based on the original version by https://github.com/videolan/libvlcsharp" or "Based on the original version by https://www.videolan.org/ " in the description.

(2) Do you want to get the source code? I can share a link.

(3) We can provide source code to any user. 3rd-party.md file already contains a list of used libraries,

**Comment by jeremyVignelles** [comment]
What about the `FontAwesome` class ? What about the `FourCCConverter` class taken from [this code](https://github.com/ZeBobo5/Vlc.DotNet/blob/35e0d0297bbba5d6756081abe17bde6d590fcdb2/src/Vlc.DotNet.Core.Interops/FourCCConverter.cs) I wrote ?
Why is there no mention of Serilog in the package description ?

Now, for [this package](https://www.nuget.org/packages/VisioForge.CrossPlatform.Redist.Windows.x86/), this seems really close to [this one](https://www.nuget.org/packages/VideoLAN.LibVLC.Windows/). It even includes an old version of [a file I wrote](https://github.com/mfkl/libvlc-nuget/blob/master/build/VideoLAN.LibVLC.Windows.targets), obviously without proper attribution.
What benefits does it bring to have your own package that is a copy of ours, if you're not adding value to it? Why not using our package instead?

I'm really curious of what you really changed in those packages, so please post a link to the changes you made here.

**Comment by visioforge** [comment]
I don't see your copyright in the source code. All files that have copyright somewhere will have it saved. Our version is a fork.

Our package contains some custom API, for example, to enable some video effects in real-time, that missed in the original package. Also, we have a fully functional player class with effects API, custom logos, and many other things.

When I've tried to make some changes in libvlc about public video effects API, my patch was ignored. That's a reason to have VideoLAN custom packages. I was not able to update the original.

So, we'll be happy to use original packages at one day, but now we want to have a fork. It's a major reason. Our high-level classes can't use original limited API. 

Here are custom methods that used to get out and apply video effects in real-time. Maybe some simple way exists but I was not able to find it in docs or chat.

[CustomVLCAPI.txt](https://github.com/visioforge/dotnet-crossplatform-sdks-samples/files/6665810/CustomVLCAPI.txt)

Pull requests are good, but VLC still uses maillist with thousands of ignored issues.

**Comment by jeremyVignelles** [comment]
> I don't see your copyright in the source code.
I'm not taking credit for every file I wrote. I contributed to some projects, like Vlc.DotNet (MIT) and LibVLCSharp (LGPL), please credit these projects appropriately.

> When I've tried to make some changes in libvlc about public video effects API, my patch was ignored.
Then that shouldn't be a problem to state those change and document them publicly in a repository if you already sent that through the mailing list. I'd argue that it's a lot nicer than having your own package and almost claiming that it's your own work.

> Pull requests are good, but VLC still uses maillist with thousands of ignored issues.
VLC now use gitlab merge requests at https://code.videolan.org/videolan/vlc

**Comment by mfkl** [comment]
> Which one?

Ask your lawyer?

> Our package contains some custom API, for example, to enable some video effects in real-time, that missed in the original package. 

And that code is where? Any modifications you made to libvlc or libvlcsharp must be published. And still zero mention of libvlc-nuget anywhere.

Like I said,

> Until then you can remove those NuGet packages I listed. You have been violating the license for over a month already.

**Comment by visioforge** [comment]
OK. We'll switch to original packages and remove our packages from NuGet. 

I'll push the merge request to GitLab, it's about making some API public, hope will be accepted. This API is public in the Windows version but not public in the Android version, I'm not sure why.

**Comment by mfkl** [comment]
Have you published your changes from libvlcsharp in https://www.nuget.org/packages/VisioForge.CrossPlatform.Controls/?

**Comment by visioforge** [comment]
This assembly uses original libvlcsharp and does not contain any code from libvlcsharp. 

The first step for us a still to prepare patches for VideoLAN, before sending a merge request for libvlc. 

I've posted the CustomVLCAPI file above, this file was the main difference between the original libvlcsharp and our builds. Now, this file is a part of the "controls" assembly. It's partially useless without VideoLAN update, so, used for Windows only now.
